Models/Entities/ContactHeader.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Task_15.Models.Customers;

namespace Task_15.Models.Entities
{
    public class ContactHeader : BaseEntity
    {
        [Required(ErrorMessage = "zorunlu alan ")]
        public string? Title { get; set; }
        [Required(ErrorMessage = "zorunlu alan ")]
        public string? Content { get; set; }
        [Required(ErrorMessage = "zorunlu alan ")]
        public string? Description { get; set; }
        [Required(ErrorMessage = "zorunlu alan ")]
        public string? Link { get; set; }
     

        public string? FilePath { get; set; }
      
        [NotMapped]
        public IFormFile? File { get; set; }
    }
}

Areas/Admin/Controllers/ContactHeaderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Task_15.Models.Context;
using Task_15.Models.Dto.ContactHeader_Dto;
using Task_15.Models.Entities;

namespace Task_15.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactHeaderController : Controller
    {

        readonly private Task_15DbContext _context;

        public ContactHeaderController(Task_15DbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var contact = await _context.ContactHeader.ToListAsync();
           


            return View(contact);
        }

        public async Task<IActionResult> Details(string id)
        {

            var contact = await _context.ContactHeader.FindAsync(Guid.Parse(id));
            if (contact == null) return NotFound();
            return View(contact);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        => View();

        public async Task<IActionResult> Create(CreateContactHeader_Dto model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
                
            
            if (model.File == null)
            {
                ModelState.AddModelError("File", "Melumat yoxdur");
                return View(model);
            }

            if (!model.File.ContentType.StartsWith("image"))
            {
                ModelState.AddModelError("File", "Yalniz shekil fayllari qebul edilir");
                return View(model);
            }

            if (model.File.Length / 1024 >256)
            {
                ModelState.AddModelError("File", $"Hecmi {model.File.Length / 1024} kv uygun deyil");
                return View(model);
            }

            var extension = Path.GetExtension(model.File.FileName);
            var newName = $"{Guid.NewGuid()}{extension}";
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\assets\\img", newName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await model.File.CopyToAsync(stream);
            }


            ContactHeader contactHeader = new ContactHeader()
            {
                Title = model.Title,
                Description = model.Description,
                Content = model.Content,
                Link = model.Link,
                FilePath = newName
            };

            await _context.ContactHeader.AddAsync(contactHeader);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {

            var contactHeader = await _context.ContactHeader.FindAsync(Guid.Parse(id));
            if (contactHeader == null) return NotFound();
            if (!ModelState.IsValid) return View(contactHeader);

            UpdateContactHeader_Dto updateContact = new UpdateContactHeader_Dto()
            {
                Id = contactHeader.Id.ToString(),
                Description = contactHeader.Description,
                Content = contactHeader.Content,
                Link = contactHeader.Link,
                FilePath = contactHeader.FilePath,
            };
            return View(updateContact);
        }

        public async Task<IActionResult> Update(UpdateContactHeader_Dto model)
        {
            if (model.File == null)
            {
                ModelState.AddModelError("File", "Melumat yoxdur");
                return View(model);
            }
            if (!model.File.ContentType.StartsWith("image"))
            {
                ModelState.AddModelError("File", "Yalniz shekil fayllari qebul edilir");
                return View(model);
            }

            if (model.File.Length / 1024 > 256)
            {
                ModelState.AddModelError("File", $"Hecmi {model.File.Length / 1024} kv uygun deyil");
                return View(model);
            }

            var extension = Path.GetExtension(model.File.FileName);
            var newName = $"{Guid.NewGuid()}{extension}";
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\assets\\img", newName);

            using (var stream = new FileStream(path, FileMode.CreateNew))
            {
                await model.File.CopyToAsync(stream);
            }
            ContactHeader contact = new ContactHeader();
            contact.Title = model.Title;
            contact.Description = model.Description;
            contact.Content = model.Content;
            contact.FilePath = newName;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var contactid = await _context.ContactHeader.FirstOrDefaultAsync(cont => cont.Id == Guid.Parse(id));

            if (contactid == null) return BadRequest();
            _context.ContactHeader.Remove(contactid);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/ContactHeader/Create.cshtml
@using Task_15.Models.Dto.ContactHeader_Dto

@model CreateContactHeader_Dto
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <div class="card-title">Create Contact</div>
            <hr>
            <form asp-controller="ContactHeader" asp-action="Create" asp-area="Admin" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="@Model.Title"></label>
                    <input asp-for="@Model.Title" class="form-control" id="input-1" placeholder="Enter Your Title">
                    <span asp-validation-for="@Model.Title"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Content"></label>
                    <input asp-for="@Model.Content" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.Content"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Description"></label>
                    <input asp-for="@Model.Description" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.Description"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Link"></label>
                    <input asp-for="@Model.Link" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.Link"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.File"></label>
                    <input asp-for="@Model.File" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.File"></span>
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-light px-5"><i class="icon-lock"></i> Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

Areas/Admin/Views/ContactHeader/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Areas/Admin/Views/ContactHeader/Index.cshtml
@model List<ContactHeader>
<div class="col-lg-12">
    <div class="card">
        <div class="card-body" style="display:flex;  align-items:center; justify-content:space-between; flex-direction:column ">
            <h5 class="card-title">Model Table</h5>

            <a href="/admin/contactheader/create" class="btn btn-blue">Create</a>

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">№</th>
                            <th scope="col"> Title</th>
                            <th scope="col">Content</th>
                            <th scope="col">File</th>
                            <th scope="col">Description</th>
                            <th scope="col">Create Date </th>
                            <th scope="col">Update Date </th>
                            <th scope="col">Update </th>
                            <th scope="col">Delete </th>
                            <th scope="col">Details </th>
                        </tr>
                    </thead>
                    <tbody>
                 @foreach(var data in Model)
                        {
                            <tr>
                                <td>@data.Id.ToString().Substring(0,3)...</td>
                                <td>@data.Title</td>
                                <td>@data.Content</td>
                                <td>@data.FilePath</td>
                                <td>@data.Description</td>
                                <td>@data.CreatedDate</td>
                                <td>@data.UpdatedDate</td>
                                <td> <a href="/admin/contactheader/update/@data.Id">Update</a></td>
                                <td>
                                    <form asp-controller="ContactHeader" asp-action="Delete" asp-area="admin" asp-route-id="@data.Id">
                                        <a href="/admin/contactheader/delete/@data.Id">Delete</a>
                                    </form>
                                </td>
                                <td> <a href="/admin/contactheader/details/@data.Id">Details</a></td>
                            </tr>
                        }

                     
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/ContactHeader/Update.cshtml
@using Task_15.Models.Dto.ContactHeader_Dto

@model UpdateContactHeader_Dto
<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <div class="card-title">Create Contact</div>
            <hr>
            <form asp-controller="ContactHeader" asp-action="Update" asp-area="Admin" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="@Model.Title"></label>
                    <input asp-for="@Model.Title" class="form-control" id="input-1" placeholder="Enter Your Title">
                    <span asp-validation-for="@Model.Title"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Content"></label>
                    <input asp-for="@Model.Content" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.Content"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Description"></label>
                    <input asp-for="@Model.Description" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.Description"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Link"></label>
                    <input asp-for="@Model.Link" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.Link"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.File"></label>
                    <div  style="display:block">
                        <img style="width:100px; height:100px; object-fit:cover" src="~/assets/img/@Model.FilePath" alt="@Model.FilePath" />
                    </div>

                    <input asp-for="@Model.File" class="form-control" id="input-2" placeholder="Enter Your File">
                    <span asp-validation-for="@Model.File"></span>
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-light px-5"><i class="icon-lock"></i> Create</button>
                </div>
            </form>
        </div>
    </div>
</div>